# Generated by Django 2.1.4 on 2019-01-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabetic_code', models.CharField(max_length=3)),
                ('numeric_code', models.IntegerField()),
                ('currency', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.FloatField()),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_from', to='exchange.CurrencyCode')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_to', to='exchange.CurrencyCode')),
            ],
        ),
    ]
